### ISSUE TITLE
Halogenbirne im Klo

### ISSUE THREAD

**Issue by andz82** [muccc/spacefoo#10]
Halogenbirne im Klo wechseln bevor die zweite auch kaputt ist. Und vlt auch das Klo putzen ;)

**Comment by saerdnaer** [comment]
Was ist das den genau für eine und wo kauft man so Zeug am besten?

**Comment by codec** [comment]
Ich find ja die Beleuchtung mit nur einer Birne viel angenehmer. :smile:

**Comment by saerdnaer** [comment]
Wenn das Niedervolt und ein konventioneller Trafo ist, geht die andere jetzt aber schneller kaput weil die Energie für zwei Lampen jetzt auf eine geht.

**Comment by saerdnaer** [comment]
Ist ne osram decostar 51s, 12v 50w 38 grad austreuwinkel

**Comment by saerdnaer** [comment]
Zum Thema Trafo:
![](https://cloud.githubusercontent.com/assets/40266/3987786/6144273a-28a9-11e4-9a64-32e2fea866dc.jpeg)

**Comment by saerdnaer** [comment]
Ich hab mal ne gebrauchte von Zuhause eingebaut, hat zwar nur 35W sollte aber auch reichen.
