### ISSUE TITLE
Luftschleuse: Zusätzlichen AP für Vordertür

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#104]
Aktuell reicht das Luftschleusen WLAN nur für die Tür in den Hinterhof, aber nicht bis vor den Haupteingang an der Schleißheimerstraße.
* [ ] von Hintertür zur Vordertür: VLAN schalten oder extra Kabelweg schaffen 
* [ ] WLAN Router über Vordertür deployen
* [ ] …

**Comment by morawekj** [comment]
Haupteingang ist hinten per festgelegter Definition

**Comment by pc-coholic** [comment]
Ich bin ja auch ein großer Freund vom Eingang an der Straßenseite - und das funktionierte ja auch schon Mal...

Es wurde zwar nicht auf dem Plenum diskutiert, aber ich meine mich zu erinnern, dass die WLan-Repeater-Infrastruktur wieder abgebaut wurde, nachdem sie buggy war und man Leute dazu bringen wollte von hinten reinzugehen, um sicherzustellen, dass der Clubstatus auch korrekt gesetzt ist.

Ich finde, da kann man ruhig nochmal drüber sprechen, ob das wirklich notwendig ist und ob man nicht wieder den Zugang auch von vorne aktiver unterstützen möchte.

"Haupteingang ist hinten per festgelegter Definition" von @morawekj halte ich dementsprechend für einen diskussionsfähigen Punkt. Tatsächlich per [Plenums-Definition](https://wiki.muc.ccc.de/intern:plenum-2014-04#hardware_schluessel_verteilung) ist hingegen festgelegt, dass die Hardware-Schlüssel nur zur Notöffnung verwendet werden sollen und ansonsten versiegelt aufbewahrt werden sollten. Und den Punkt nehmen wir ja auch nicht so 100%ig ernst ;-)

**Comment by saerdnaer** [comment]
Wir haben schon einen user openfront@ o.ä. der die Funktionalität auf Layer 7 implementiert, Problem ist halt aktuell nur das Layer 1 nicht bis vor die besagte Tür reicht. Man muss beim Umsetzen von #48 halt nur schauen, das das Netz das im Luftschleusen WLAN ist auch getaggt oder per zweitem Ethnernet-Interface per Kabel exposed wird.

**Comment by saerdnaer** [comment]
Luftschleuse ist jetzt über die regulären SSIDs erreichbar, Problem dadurch gelöst
