### ISSUE TITLE
Roter Labelwriter: Band leer

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#107]
Von Andi's rotem Labelprinter „P-touch 900“ im oberen Labor wurde wohl gestern das Labelband komplett drained.
Bitte ein neues ordern. ktnx im Voraus.

**Comment by saerdnaer** [comment]
Für begründete Beschriftungsvorfälle hab ich noch noch welches in anderen Farben auf Lager. Trotzdem wäre es vermutlich sinnvoll auch wieder grün im Angebot zu haben.

**Comment by winks** [comment]
Wie werden unbegründete Beschriftungsvorfälle dokumentiert? Finde das Beschriftungsvorfallanzeigeformular im wiki nicht.

**Comment by saerdnaer** [comment]
Grünes Beschriftungsband ist wieder in ausreichender Anzahl, allerdings in schlechterer Qualität verfügbar. Labelgerät ist im Studio oder im Rack aufzufinden.
