### ISSUE TITLE
Farbfernseher hat fascht keinen Toner mehr.

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#108]
Unser getreuer „Farbfernseher“, Modell „HP Color Laserjet 4700n“ im Hauptraum, jault, heult und meckert dass der Toner nahezu leer sei.

**Comment by fpletz** [comment]
Farbfernseher funktioniert.

**Comment by ACTPic** [comment]
Der Farbfernseher meldet, alle Tonerkartuschen (Farbe und schwarz) seien leer, ignorieren sei aktiv.
Er macht lustige Schlieren auf die Ausdrucke.
