### ISSUE TITLE
Kalender ICS download kaputt --> Überbus-Probleme?

### ISSUE THREAD

**Issue by dergigo** [muccc/spacefoo#111]
http://api.muc.ccc.de nicht erreichbar. Überbus down?

**Comment by saerdnaer** [comment]
Jemand sollte echt mal ein Monitoring dafür bauen...

**Comment by saerdnaer** [comment]
Laut Argv wurde das Problem im core-Switch behoben. Es waren alle VMs im Club betroffen. Der besagte Host ist für mich wieder erreichbar.
