### ISSUE TITLE
WC-Ampel-Sensor

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#115]
Die WC-Ampel steht (so sie angeschaltet ist) auf dauergrün. Der Sensor der die Türverriegelung erkennt ist b0rk.

**Comment by saerdnaer** [comment]
Habe gestern einen Schalter zum abschalten der Ampel eingebaut. Bitte Type des "Sensor-Schalter" bei Reichelt raussuchen, dann bestelle ich den mit.

**Comment by fpletz** [comment]
Wurde gefixed.
