### ISSUE TITLE
PoE-Switch für Rasπ-Farm im NOC

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#118]
Nachdem es leider niemand auf die Reihe bekommt, eine neue Shellserver-VM auf Gustl aufzusetzen, es aber dringend nötig ist, wieder mal das Deltadokument^W^Wdie SinusCosinus-Dateien für Member zu leaken, haben wir im DarkFasel angedacht, einfach einen PoE-Switch ins NOC zu integrieren, damit jede{,r} einfach {ihr,sein}en eigenen Raspπ unterbringen kann.
Es wäre schön, wenn der Vorstand von den Mitgliedsbeiträgen sowas anschaffen könnte.
Beispielquellen: https://geizhals.de/?cat=switchgi&xf=13106_RJ-45+PoE%2B%7E13342_24

**Comment by saerdnaer** [comment]
Es gibt bereits einen POE Swich, aber bitte beachte auch die Reglungen bezüglich Colocation im Club. Das es keine neue Shellserver VM gibt ist aus meiner sicht ne aktive Entscheidung, können wir aber gerne auch mal im Plenum besprechen.

**Comment by atdotde** [comment]
Was ist "die Reglungen bezüglich Colocation im Club. "?

**Comment by saerdnaer** [comment]
Für die genaue Formulierung müsste man jetzt nochmal in den Plenums Protokollen nachlesen oder DaN/Argv fragen, aber aus dem Kopf: Strom und Internet muss von den entsprechenden Nutzern selbst gestellt und bezahlt werden.
