### ISSUE TITLE
Griff Haupteingangstür b0rk

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#119]
https://darkfasel.net/_matrix/media/r0/download/asra.gr/d78f87068d2af1ae2552c0148ebd20ecc126ea73/20220224_135840.jpg (Kredite an a)

Momentan bitte beim Verlassen des Klubs prüfen ob die Vordertür auch net durch Aufdrücken aufgeht.

**Comment by saerdnaer** [comment]
Wurde gestern Abend von iggy mit zwei Nieten behoben
