### ISSUE TITLE
Geldwechsler b0rk

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#121]
Der Geldwechselautomat links neben der Spendenbox ist schon länger b0rk, Gerüchten zufolge, weil die SD-Karte schlapp machte.

**Comment by saerdnaer** [comment]
Afaik ist der eigentlich einfach abgeschalten weil die Features durch den Geldwechsler im Matematen übernommen werden. Sollte dem anders sein Ticket bitte wieder öffnen.

**Comment by pc-coholic** [comment]
Beides ist korrekt.

Die SD-Karte ist durch, aber weil der Matemat auch wechseln kann (und das mit dem Schein-Recycler sogar besser als der Fnordload) ist die Motivation das zu reparieren gerade denkbar gering.

Wenn wir irgendwann Mal was machen, was nicht am Matematen abgebildet werden kann, kann man das ja wieder reaktivieren.
