### ISSUE TITLE
Luftschleuse: SSID in Abhänigkeit vom aktuellen Clubstatus

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#18]

**Comment by robinkaranu** [comment]
Was ist hier angedacht? Ich kann aus dem Subject nicht interpolieren was das bringen soll.. :-)

**Comment by saerdnaer** [comment]
Das hat verschiedene Vorteile (s.u.), schneider meinte auch schon das er sich darum kümmert.
- man sieht beim Verbinden schon, das der Status z.B. schon member ist
- Telefone bleiben nicht mehr im Luftschleuen-WLAN nachdem aufgesperrt wurde, weil das ja seinen Namen ändert
- ...

**Comment by robinkaranu** [comment]
Ah - danke für die Erklärung. Nun hab ichs verstanden.. Dafür! :+1:

**Comment by schneider42** [comment]
Ping mich jemand am wochenende :)

**Comment by pc-coholic** [comment]
@schneider42 Es wäre grad Mal wieder ein Wochenende ;-)

**Comment by schneider42** [comment]
Done.
