### ISSUE TITLE
Keine Mitgliedsanträge auf dem Unsafe mehr

### ISSUE THREAD

**Issue by robinkaranu** [muccc/spacefoo#19]
Hi,

es sind keine Mitgliedsanträge mehr an der üblichen Stelle. Man[tm] sollte mal neue Drucken und dort ablegen.

**Comment by andz82** [comment]
20 Gedruckt...Toner alle...

**Comment by robinkaranu** [comment]
:+1: thx! Wo find ich die Vorlage zum selbstdrucken?

**Comment by andz82** [comment]
Auf muc.ccc.de unter "Verein"
Am 08.11.2014 14:33 schrieb krobin notifications@github.com: thx! Wo find ich die Vorlage zum selbstdrucken?
