### ISSUE TITLE
Neuen Toner fuer Farblaser besorgen

### ISSUE THREAD

**Issue by chris007de** [muccc/spacefoo#2]

**Comment by saerdnaer** [comment]
@schneider42 was ist den mit dem aktuellen? Bzw welche Farben sind leer?

**Comment by schneider42** [comment]
Schwarz wird auf jedenfall benoetigt.

**Comment by saerdnaer** [comment]
![image](https://cloud.githubusercontent.com/assets/40266/3606109/a84e5cfa-0d32-11e4-8dba-2057407e2a05.jpeg)

**Comment by andz82** [comment]
TONER ENDGUELTIG ALLE!!!!111!1EINSELF....Drucker ist so intelligent und druckt nun SW mit den 3 Grundfarben....aber nicht billiger...btw. Gelb ist auch komplett alle

**Comment by saerdnaer** [comment]
Ist auf der Agenda fürs Plenum am Montag

**Comment by saerdnaer** [comment]
Gesamt-Summe für Rebuild-Toner: 80+3x84 = 332 EUR (ggf. zuzüglich Versand)

Plenumsbeschluss vom 3. März 2015:
 Neuer Toner soll bestellt werden?
 Ja: 14
 Nein: 1
 Enthaltung: 0

**Comment by fpletz** [comment]
Wurde besorgt.
