### ISSUE TITLE
Kalender Tabelle hat jetzt auch Wochentage

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#21]
@chris007de Ich hab mal auf https://wiki.muc.ccc.de/kalender angefangen Wochentage mit einzutragen. Kommt dein Kalender Skript für den anzeigr, ical usw. damit klar oder macht das Probleme?

**Comment by dl1com** [comment]
Das muss ich dem Script erst beibringen, mach ich die Tage mal :)

**Comment by dl1com** [comment]
Erledigt: https://github.com/muccc/wiki_kalenderscraper/commit/12a6801c342d52a4c9eb31bc4aa05c09cce850f6

@fpletz bitte pullen, damits auch bei api.muc.ccc.de Wirkung zeigt, danke!

**Comment by fpletz** [comment]
@chris007de Habe ich soeben deployed. Sieht gut aus soweit ich sehe. :+1:
