### ISSUE TITLE
public tuesday howto schreiben

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#23]
z.B. mit Link zur Präsentation usw.

Sollen wir uns dazu im Club einfach mal zusammen an nen Pad sitzen?
Oder findet ihr die Idee an sich schon irgendwie blöd?

**Comment by schneider42** [comment]
Dafuer.

**Comment by saerdnaer** [comment]
@dergigo wo liegen den die Folien die du? gemacht hattest?

**Comment by saerdnaer** [comment]
Sollen wir uns Ende dieser Woche mal an ein Pad setzen?

**Comment by saerdnaer** [comment]
@fpletz Du solltest schon begründen warum das Ticket schließt. ;-)
