### ISSUE TITLE
acab.muc.ccc.de broken

### ISSUE THREAD

**Issue by fpletz** [muccc/spacefoo#24]
`acab.muc.ccc.de` is a CNAME for `ludwig.muc.ccc.de`, but it should point to `muccc.github.io` instead. See https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/.

**Comment by codec** [comment]
Nope, acab.muc.ccc.de is proxied on ludwig for SSL. But.. something's missing.

**Comment by alice-wl** [comment]
could you maybe add another alias for eg acab-201... pointing to the wiki.Then I could revive the pixlpatenpage page from purto for historicalreasons.

**Comment by codec** [comment]
No SSL for the moment
