### ISSUE TITLE
acab.muc.ccc.de ist nicht über https erreichbar

### ISSUE THREAD

**Issue by winks** [muccc/spacefoo#3]
https://acab.muc.ccc.de/ -> unknown domain: acab.muc.ccc.de

**Comment by saerdnaer** [comment]
Das ist glaube ich jetzt direkt bei Github gehostet, keine Ahnung wie weit man das beeinflussen kann.
https://github.com/muccc/acab-streetlife/tree/gh-pages

**Comment by winks** [comment]
Ticket entstand nur, weils in der Mail mit https erwähnt wurde.
Man könnte immer noch einfach 301/302-redirect auf http machen.

**Comment by codec** [comment]
Nee, liegt alles bei GitHub - kein Einfluss drauf.

**Comment by codec** [comment]
Webserver spielt jetzt Reverse Proxy zu GitHub. Yay, SSL.
