### ISSUE TITLE
CRM: Logo erstellen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#30]
> JPEG or PNG file formats and in the RGB color space with a minimum size of 1400 x 1400 pixels and a maximum size of 2048 x 2048 pixels.

Sprich am besten PNG mit 2048 x 2048 px

**Comment by saerdnaer** [comment]
@Andreoide Was war da nochmal der aktuelle Stand?

**Comment by saerdnaer** [comment]
Wenn ich mich richtig erinnere hat Caro eines gezeichnet? Wo findet man das?

**Comment by fpletz** [comment]
Seit mehr als 5 Jahren keine neuen Folgen.
