### ISSUE TITLE
Türgriff/Schloss am Sicherungskasten im Keller ist defekt

### ISSUE THREAD

**Issue by robinkaranu** [muccc/spacefoo#34]
Gerade so vorgefunden. Kaputt. Nur mit Zange o.Ä. zu öffnen.
![img_1894](https://cloud.githubusercontent.com/assets/822736/6190919/c5295be4-b3a5-11e4-99d5-bd26249a1bce.JPG)

**Comment by saerdnaer** [comment]
Das ist ein Feature ;-) 
Es soll nicht jeder (wie z.B. Handwerker) an den Sicherungen rumspielen. Jan hatte da angefangen das umzubauen aber nicht fertig gemacht.

**Comment by saerdnaer** [comment]
Inzwischen wurde der Griff von unbekannt durch eine Version ersetzt, in die ein Halb-Zylinder eingesetzt werden kann.
