### ISSUE TITLE
Anschaltstrom im Hauptraum löst F23 aus

### ISSUE THREAD

**Issue by robinkaranu** [muccc/spacefoo#35]
Der Anschaltstrom am grau-schwarzen Stromverteiler auf dem großen Tisch im Hauptraum löst immer wieder mal F23 im oberen Sicherungskasten (im Schrank nahe Küche) aus. Stromfreaks: Gibts einfache Möglichkeiten die diversen Schaltnetzteile verzögert einzuschalten? Was ist die Alternativlösung? Nicht alles über einen Verteiler feeden? Können wir den Strom messen? Wenn ja, ist er zu hoch, oder ist der Automat defekt?
- [ ] Einschaltstrom messen
- [ ] ggf. Automat durch C16 Version ersetzten (lässt höheren Einschaltstrom zu)

**Comment by saerdnaer** [comment]
Gefühlt ist das Problem in den letzten Wochen nicht mehr aufgetreten. Ticket schließen?

**Comment by schneider42** [comment]
Ist mir vor ner Woche passiert.

**Comment by saerdnaer** [comment]
Wir können ja mal einen [HexaBus-Plug+](https://github.com/mysmartgrid/hexabus/wiki/HexaBus-Plug) dazwischen hängen und schauen was da so für Ströme auftreten.
Oder ist das eher zu viel Strom für den Plug?

**Comment by schneider42** [comment]
Ich glaube nicht, dass es moeglich ist damit den Einschaltstrom zu messen.

**Comment by robinkaranu** [comment]
Ich hab das Problem lange nicht mehr beobachtet, ich machs erstmal zu..
