### ISSUE TITLE
Hauptraum: Lange Flipdotzeile

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#38]
- [x] Probleme mit der Stromversorgung/Netzteil beheben
- [x] Pixelfehler beheben
- [x] Code auf Github stellen
- [ ] Stromsparlösung im Wiki dokumentieren @dergigo

**Comment by saerdnaer** [comment]
https://wiki.muc.ccc.de/flipdot:start#zeile

> Es gibt mehrere Möglichkeiten die Zeile anzusprechen:
> - UDP: Wie alle Displays beherrscht auch die Zeile ein triviales UDP-Protokoll: 2001:7f0:3003:235e:ba27:ebff:fe89:4cd2 Port 2323
> - In #ccc auf darkfasel: Alle Posts, die “Alarm” enthalten sowie Topic-Änderungen werden angezeigt.
> - https://muc.pads.ccc.de/flipdot wird angezeigt (BETA)

**Comment by fpletz** [comment]
@dergigo Wo ist der Code?

**Comment by saerdnaer** [comment]
"Auf dem Device", "Login steht im Wiki".

**Comment by robinkaranu** [comment]
https://github.com/muccc/flipbot Passwort steht im Wiki, Source war auf dem Device.

**Comment by saerdnaer** [comment]
@dergigo Kannst du den Code bei Gelegenheit mal auf dem Projektor o.ä. erklären?

**Comment by fpletz** [comment]
@saerdnaer Damits nur die Anwesenden (also niemand) mitkriegen? Doku > Erklärbären.

**Comment by saerdnaer** [comment]
@fpletz Ich dachte jetzt an nen Mitschnitt mit Ton. ;-)

**Comment by schneider42** [comment]
Warum nicht mal ein Video probieren?
