### ISSUE TITLE
Ethernet-Schnittstelle des Projektors richtig nutzen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#39]
Unsere Projektor ist per Ethernet ans Hardware-Netz angeschlossen und hat die Macadresse 00:18:23:28:47:30
- [x] Macadresse von Argv im DHCP Server eintragen lassen
- [x] für eines der verfügbaren Protokolle zur Fernsteuerung entscheiden
- [x] Ein- und Ausschaltbefehl heraussuchen und als Skript implementieren
- [x] In OpenHAB Instanz auf Uberbus-VM integrieren

**Comment by saerdnaer** [comment]
@pc-coholic Hattest du bei unserem Test am WE auch per Telnet angesprochen?

**Comment by pc-coholic** [comment]
Ja, hatte ich.

Crestron hat mit der Android-App nicht direkt geklappt - hatte ich aber auch nicht weiter eingehend getestet...

**Comment by saerdnaer** [comment]
Ist jetzt erledigt, vgl. 
https://github.com/muccc/openhab-config/commit/8e7e3f94bb28248d152e6037f67ea71ec46d8fcd

Im OpenHAB UI gibt es jetzt einen neuen Umschalter 'Projektor':

<img width="504" alt="temp" src="https://cloud.githubusercontent.com/assets/40266/11325784/24f7aee2-9157-11e5-85d1-aa1fa9616d65.png">
