### ISSUE TITLE
lists.muc.ccc.de für manche Browser nicht per https erreichbar

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#4]
Das aktuell dort verwendete Zertifikat wurde revoked. Soweit ich codec verstanden habe, soll der Mailman langfristig auf ne andere Maschine ziehen, weswegen das Problem durch nen reverse-Proxy fuer die Domain auf der Wiki-VM geloest werden soll?

**Comment by winks** [comment]
Funktioniert momentan aber wunderbar (seit gestern abend): https://lists.muc.ccc.de

**Comment by codec** [comment]
@winks Nee, Zertifikat immernoch revoked. ;)
@saerdnaer Reverse Proxy als Provisorium bis der Listserver umzieht ...

**Comment by winks** [comment]
Much confuse, very green cert

![foo](http://stuff.art-core.org/temp/Clipboard02.png)

**Comment by codec** [comment]
@winks Windows :shit:

**Comment by saerdnaer** [comment]
@winks Dein Browser überprüft nicht ob das Zertifikat revoked ist.

**Comment by winks** [comment]
Ja, aber auch mein curl oder sonstwas nicht.
Ich sag ja nicht, dass man es nicht fixen soll, aber wer merkt das _überhaupt_, dass es revoked ist?

Das Ticket sagt "nicht per https erreichbar".

**Comment by codec** [comment]
Fixed
