### ISSUE TITLE
Papier fuer Farblaser besorgen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#40]
Nachdem wir jetzt wieder Toner haben ist leider das Papier alle. Wo besorgen wir das am besten?

**Comment by saerdnaer** [comment]
Plenum 2015-04: DaN kümmert sich darum

**Comment by robinkaranu** [comment]
Derzeit ist Papier im Drucker, (größere) Vorräte habe ich auf Anhieb aber nicht mehr gefunden. Das offensichtlich verwaiste Ticket Issue mach ich aber mal zu.
