### ISSUE TITLE
Auf Mailserver Anti-Spam Maßnahmen umsetzen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#41]
Bitte auf Zonk oder welche VM jetzt grade Mail bzw. Mailman macht ein paar Anti-Spam Maßnahmen ergreifen: 
Durch die ganzen Mailinglisten und -Forwards (-owner, -bounches etc) bekommen die Spam-Mails richtige Header wodurch das Filtern danach wieder schwieriger wird. Zusätzlich fliegen regelmäßig Leute mit sehr gutem Spamfilter von Mailinglisten weil zu viele Mails von ihren Adressen bounchen. Die entsprechende Benachrichtigung von Mailman an die Nutzer das dass passiert ist, kommt dann leider auch nicht an, weil Zonk da gerade geblacklistet ist (Quelle: @pc-coholic).

Ich denke für den Anfang reicht erst mal policyd-weight oder so. Wenn das nichts bringt kann man ja ggf. noch anders nachbessern.

**Comment by fpletz** [comment]
```c
return -EACCES;
```

**Comment by codec** [comment]
Description please? :)

**Comment by saerdnaer** [comment]
Done.

**Comment by pc-coholic** [comment]
@codec Kannst du da bitte was machen? Irgendwas? Die Menge an Spam, die ich jeden Tag aus den Mod-Queues rausmoderieren darf ist echt nicht mehr lustig...

Nen SpamAssassin reinzuhängen, sodass man dann direkt in Mailman den Header rausfiltern kann sollte doch nicht ganz unmöglich sein?

**Comment by codec** [comment]
Ich versuche mich die Woche drum zu kümmern. Es gibt leider 1-2 Abhängigkeiten mehr als nur den policyd und seine Config reinzuwerfen. :(

Kann mich auch gerne jemand in den Abendstunden nochmal pingen..

**Comment by schneider42** [comment]
ping

**Comment by pc-coholic** [comment]
> 32 Spam-mails im Filter in 3 Tagen - das wird nicht weniger sondern aktuell immer mehr...

@codec Kannst du bitte nochmal gucken, was da machbar wäre? Danke!

**Comment by codec** [comment]
Bisschen was am Mailserver geschraubt. Mal sehen was jetzt alles kaputt geht oder nun moeglich wird. ;)

**Comment by pc-coholic** [comment]
@codec So wie ich das sehe, scheint noch alles zu funktionieren :-)

Spam-Mails werden aber noch nicht im Header getaggt, oder?

**Comment by saerdnaer** [comment]
@codec hattest du das neulich wieder zurück rollen müssen?

**Comment by codec** [comment]
@saerdnaer Korrekt :disappointed: werde die Tage nochmal daran rumbasteln, wenn sich Zeit findet.

Opinions bzgl. Filtermaßnahmen? (ausgeschlossen Greylisting - das ist doof ;))

**Comment by saerdnaer** [comment]
@codec Any updates?

**Comment by derchrisuk** [comment]
Schon mal https://www.mailscanner.info/ angeschaut?

**Comment by fpletz** [comment]
Oder https://www.rspamd.com/

**Comment by saerdnaer** [comment]
Fpletz hat inzwischen ein Briafzentrum mit rspamd via Nix eingerichtet.
