### ISSUE TITLE
Neues Info Plakat drucken

### ISSUE THREAD

**Issue by codec** [muccc/spacefoo#42]
Das Infoplakat draussen wurde schon laenger nicht mehr getauscht. Lt. Info ist der naechste Public Dienstag im August. Bald jaehrt sich also der Zettel. :)

**Comment by codec** [comment]
@cko @seelmann Ihr habt das letztes Mal gemacht, oder?

**Comment by fpletz** [comment]
Vielleicht sollte man in der folgenden Version des Plakats nur auf die Webseite verweisen oder eventuell auf die 2. Donnerstag des Monats Regel als Daumenpeilung hinweisen.

**Comment by dl1com** [comment]
Die Stelle des Plakats wo die Termine stehen leer lassen und einen kleineren Zettel mit den aktuellen Terminen auswechselbar draufkleben/anheften.

**Comment by saerdnaer** [comment]
Ich wäre auch dafür eine Lösung zu schaffen um die man sich nicht jedes halbe Jahr  mit externen Resourcen (DinA2 Druck) kümmern muss.

@chris007de Mit weißem oder schwarzen Hintergrund?

**Comment by saerdnaer** [comment]
@seelmann Macht mal einen Vorschlag. Wir nehmen weiß als Hintergrund für die "Patches"
@markus2342 merkt noch an, dass die Website-URL mit https:// geschrieben werden sollte.

**Comment by codec** [comment]
Was @chris007de und @fpletz sagen: :+1:

Weißer Hintergrund fällt IMO mehr auf als der schwarze und ist vielleicht "umweltschonender". ;)

**Comment by seelmann** [comment]
@codec @saerdnaer Weißer Hintergrund für das ganz Plakat, oder nur für den "Patch" Bereich?

**Comment by codec** [comment]
Ich wuerde gleich mal das ganze neu drucken (mit weißem Hintergrund) und dabei die Patchflaechen vorsehen, weil das alte eh versifft ausschaut (ist vielleicht nur die Plastikscheibe davor).

**Comment by pc-coholic** [comment]
Haben wir in Zukunft nicht eh einen Schwung von den Nokia-LCDs, die man einfach ins Plakat integrieren kann? (Nur so ne Idee...)

**Comment by seelmann** [comment]
So hier ist mal ein Entwurf: https://github.com/muccc/texts_posters_presentations/commit/4e213d9ebc99b53527ad30e149ea1430b33e6ac8
Direkter Download: https://github.com/muccc/texts_posters_presentations/raw/master/poster_veranstaltungen.pdf

**Comment by seelmann** [comment]
Update: radio jetzt mit https, thx Markus: https://github.com/muccc/texts_posters_presentations/commit/fad18528dd1e888d0885895ec1d4214ee2d94b0f

**Comment by saerdnaer** [comment]
https://wiki.muc.ccc.de/public:treffen sollte eher https://muc.ccc.de/treffen sein. 
Man kann man sich die PDF Version einfach per Inkscape generieren, oder? 
Sollen wir da nochmal unser Logo mit aufführen? Soll ich mich da wieder um der Druck kümmern oder hatte auch jemand anders zugang zu einem A2 Drucker?

**Comment by seelmann** [comment]
- URL ist gefixt.
- Ja, PDF wird aus Inkscape mittels "Save as..." generiert, ich habe immer 600dpi eingestellt.
- Das Logo hab ich extra rausgenommen, da mit der untere Bereich als "Patchfeld" verwendet werden kann. Das Logo ist ja sowieso gleich daneben in der Tür ganz groß vorhanden.
- Wenn du es Drucken kannst wäre super, wenn nicht gehe ich bei 'nem Copyshop vorbei.

**Comment by saerdnaer** [comment]
Ich hab den Druck mal in Auftrag gegeben.

**Comment by saerdnaer** [comment]
Hängt inzwischen seit ein paar Wochen
