### ISSUE TITLE
Keine deutschen Umlaute per „!Alarm“-Kommando

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#44]
Hallo LeutInnen,

zur Zeit mutiert mein „ß“, das ich in einer „!Alarm“-Zeile auf die innere linke Flipdotzeile pfostierte, zu einem Fragezeichen („?“). Es sollte™ UTF-8-Support implementiert werden, und die verwendete Font mindestens um die offiziellen und/oder inoffiziellen deutschen UmlautInnen ergänzt werden.

Mit freundlichen Grüßen,

APic

**Comment by saerdnaer** [comment]
Liegt laut Gigo daran, dass UTF8 bei dem Bot nicht funktioniert.

**Comment by fpletz** [comment]
Problem nicht behoben.

**Comment by saerdnaer** [comment]
@ACTPic: Schreib am besten einen Patch für den Font. vgl. https://github.com/muccc/flipbot/blob/master/_willie/modules/alarm.py#L9-L16 

```
 "A": [
    [0,0,0,0,0],
    [0,1,1,0,0],
    [1,0,0,1,0],
    [1,1,1,1,0],
    [1,0,0,1,0],
    [1,0,0,1,0],
  ],
```

Am besten mit allen Zeichen du gerne im Topic verwendet würdest.

**Comment by saerdnaer** [comment]
Nachtrag: Im Font ist ÄÖÜ schon mit drin, ß ist nicht mit dabei, sind allerdings nur Großbuchstaben... Sprich nen Workaround wäre ß einfach durch SS zu ersetzen

**Comment by ACTPic** [comment]
Okay, danke für den Pointer. Ich setze mal auf meinen Dot-Plan, dass ich beizeiten™ die kleinen Umlaute und das scharfe ß in die Font hineinpatchen werde.

**Comment by saerdnaer** [comment]
Wie man dem oben verlinkten commit (https://github.com/muccc/flipbot/commit/7bc7d1e1c5392d197b641397c946f72482d79a8f) entnehmen kann, hab ich erst mal nen Workaround eingebaut ß wird durch SS ersetzt und das Problem mit ÄÖÜ behoben. Deswegen ist das Ticket jetzt ja auch zu. Aktuell gibt es in dem Font übrigens keine Kleinbuchstaben.
