### ISSUE TITLE
HSTS für wiki.muc.ccc.de einrichten

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#45]

**Comment by saerdnaer** [comment]
@codec Wer außer @alice-wl hat alles Zugang auf die Wiki VM und könnte das potenziell einrichten?

**Comment by codec** [comment]
Wir haben's doch schonmal davon gehabt, dass wir das nicht machen wollen wegen dem CACert Unsinn.

**Comment by saerdnaer** [comment]
Die Begründung macht überhaupt keinen Sinn. Es geht nur darum das wenn man einmal per HTTPS drauf war, das man dann auch in Zukunft automatisch per HTTPS auf dem Webserver ist. Wenn man seine Certs nicht im Griff hat ist man also gar nicht betroffen.

**Comment by codec** [comment]
Deine Aussage macht genauso überhaupt keinen Sinn.

**Comment by codec** [comment]
https://letsencrypt.org/2015/06/16/lets-encrypt-launch-schedule.html dann koennte man auch halbwegs schmerzfrei HSTS anschalten.

**Comment by saerdnaer** [comment]
Ich würde mich freuen wenn du mir das im Club mal genauer erklären könntest. Ich versteh nicht warum das aus deiner Sicht eine Voraussetzung dafür ist.

**Comment by codec** [comment]
kA, wo meine Mail versumpft ist beim antworten:

Ja, lass mal quatschen. Vielleicht findet man die Basis für die Entscheidung sogar noch in einem der Protokolle.
