### ISSUE TITLE
Netzteilhack auch für großes Flipdotdisplay umsetzen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#46]
vgl. Zeile

**Comment by saerdnaer** [comment]
Kann das nur @morawekj oder weiß inzwischen auch jemand anders wie das geht?

**Comment by saerdnaer** [comment]
Plenum 2015-07: Es weiß nur Jan wie das geht. Nach dem 32C3.

**Comment by saerdnaer** [comment]
@morawekj Reminder ;-)

**Comment by morawekj** [comment]
Durch Gigo und Schneider umgesetzt, Heldenstatus erteilt.
