### ISSUE TITLE
Public Tuesday every Tuesday

### ISSUE THREAD

**Issue by fpletz** [muccc/spacefoo#47]
- [ ] Webseite anpassen, Führung/Präsi optional
- [ ] im Kalender eintragen
- [ ] Namensschilder bevorraten
- [ ] Automatisch mit Link per Twitter announcen

**Comment by saerdnaer** [comment]
Termine erst mal nur bis zum Camp eintragen, korrekt?
Wollt ihr das mit den Namensschildern auch heute Abend schon durchziehen?

**Comment by fpletz** [comment]
Ich werde heute abend leider nicht vorbeikommen koennen, beim naechsten Mal.

**Comment by saerdnaer** [comment]
@fpletz Kannst du mal schauen wie weit die einzelnen Subtasks inzwischen erledigt wurden?

**Comment by fpletz** [comment]
Nix.
