### ISSUE TITLE
Luftschleuse should support ed25519 keys

### ISSUE THREAD

**Issue by codec** [muccc/spacefoo#48]
Luftschleuse will reject logins using keys of type ssh-ed25519.

_Edit: It probably only supports ssh-rsa and ssh-dss currently ;)_

**Comment by robinkaranu** [comment]
+1

**Comment by codec** [comment]
@schneider42 Kann ich da irgendwas machen? Was wäre die Schleuse überhaupt für ein System?

Edit: ich hatte auf der alten mal root, aber seit der neuen nicht mehr.

**Comment by oida** [comment]
+1
würde auch fixen wenn mir wer den access gibt :)

**Comment by schneider42** [comment]
Das ist ein carambola 2 mit einem OpenWRT. Ich bin dafuer das durch einen rpi mit debian/fedora zu ersetzen.

**Comment by robinkaranu** [comment]
Ich würde einen BeagleBone Black sponsorn wenn das zuträglich ist.

**Comment by codec** [comment]
bump. Kommt wiederholt auf das Thema.

**Comment by codec** [comment]
bump

**Comment by codec** [comment]
bump

**Comment by schneider42** [comment]
Jemand sollte mal nen rpi einbauen.

**Comment by derchrisuk** [comment]
Was muss der rpi denn koennen?
Reichen die GPIOs, oder wird noch ein RS485 benoetigt?

**Comment by schneider42** [comment]
Der master controller wird ueber USB angeschlossen

**Comment by schneider42** [comment]
Wlan brauchts halt. Eventuell mit externer Antenne angeloetet.

**Comment by morawekj** [comment]
Boards mit Intergiertem Wlan sind gar nicht so häufig, Anschluss an den Master Controller erfolgt via serieller Schnittstelle (TTL Pegel)
Moderne Ausführung, mit dem was wir haben:
http://www.8devices.com/products/rambutan
http://shop.8devices.com/rambutan-dvk
720 MHz QCA 9557 CPU, 128 MB Ram und 128 MB Flash

**Comment by morawekj** [comment]
Hardware Umbau schätze ich mit 2 Stunden ein, 2 Antennen sind sogar möglich, dualband WLAN

**Comment by schneider42** [comment]
Ich will eigentlich nicht nochmal ein halb gepflegtes OpenWRT Geraet da einbauen.

**Comment by schneider42** [comment]
Das OpenWRT von 8devices hat zum letzten mal im Mai 2016 von upstream gepullt: https://github.com/8devices/openwrt-8devices/commits/master

**Comment by morawekj** [comment]
Alternativ, Orange PI
Kleinster hat schon WLAN http://www.orangepi.org/orangepizero/

Gibt mehrere Modelle, Github scheint recht aktuell zu sein.

**Comment by derchrisuk** [comment]
Wieso kein rpi ?

**Comment by schneider42** [comment]
Ja, ein RPI3 wuerde bestens funktionieren.

**Comment by derchrisuk** [comment]
Waere der neue Zero W eine alternative ?

**Comment by morawekj** [comment]
Zero W hat kein LAN Anschluss, beim 3 er RPI gibt es keine Antennebuchse, ist halt gefrickel

**Comment by derchrisuk** [comment]
https://www.dorkbotpdx.org/blog/wramsdell/external_antenna_modifications_for_the_raspberry_pi_3

**Comment by morawekj** [comment]
OK, auf der Unterseite bekommt man UFL drauf, wenn einen besorgt mache ich die Adaptierung auf Antenne und Konnektierung zum Masterkontroller

**Comment by derchrisuk** [comment]
Dann bringe ich die Tage einen RPI3 vorbei.

**Comment by saerdnaer** [comment]
@derchrisuk Was ist den da der aktuelle Stand?

**Comment by derchrisuk** [comment]
Der Pi ist schon seit laengerem im Club und wurde bereits durch @morawekj gemodded.

**Comment by saerdnaer** [comment]
@derchrisuk @schneider42 Sollen wir das in den nächsten Wochen mal angehen? Bei der Gelegenheit könnten wir auch gleich nen neuen Akku einbauen (muss noch bei Reichelt o.ä. bestellt werden), und das Kabel zum Schloss der Hintertür austasuschen (Kabel ist schon da, muss man sich nur mal Zeit zum zusammenlöten nehmen...)

**Comment by fpletz** [comment]
Es gibt schon einen Pi im Club?! Wo ist der? Ich würde weitermachen.

**Comment by derchrisuk** [comment]
Konnte mich gar nicht mehr drann errinern das ich schon mal einen rpi gedroppt hatte.
Aber wir haben ja nun einen neuen fuer luftschleuse3

**Comment by fpletz** [comment]
Fixed.
