### ISSUE TITLE
Bilder von luftschleuse2 machen und ins Wiki hochladen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#49]
vgl. https://wiki.muc.ccc.de/luftschleuse2

**Comment by derchrisuk** [comment]
3x Bilder hochgelden
Auf, Zu und Klingel vorne

**Comment by saerdnaer** [comment]
THX!

Hab die Bilder jetzt auch auf https://wiki.muc.ccc.de/luftschleuse2 eingebunden.
