### ISSUE TITLE
Anzeigr bootet nicht mehr

### ISSUE THREAD

**Issue by dl1com** [muccc/spacefoo#5]
Anscheinend hat die SD Karte nen Schaden - bleibt mit "mmc0: Timeout waiting for hardware interrupt" beim booten hängen.

proposal: Neue SD Karte, Raspbian neu aufsetzen :-/

**Comment by saerdnaer** [comment]
Einfach rüberkopieren geht nicht?

**Comment by dl1com** [comment]
gefixt, neue SD Karte installiert und raspbian neu aufgesetzt.
