### ISSUE TITLE
hqstate.jpg implementieren

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#50]
Früher gab es unter https://brezn.muc.ccc.de/~codec/cgi-bin/hqstate.jpg ein Bild das den jeweils aktuellen Club-Status angezeigt hat. Es wäre cool wenn das jemand von euch auch wieder auf http://api.muc.ccc.de/hqstate.jpg implementieren würde.

Bei der Gelegenheit kann auch gleich der Cronjob durch die entsprechende Funktion (https://github.com/muccc/monolith/blob/master/schleuse.py#L245-L248)  des Monolithen ausgetauscht werden.

**Comment by fpletz** [comment]
Und http://api.club.muc.ccc.de/hqstate.jpg :)

**Comment by saerdnaer** [comment]
Ist doch eh das selbe, da api ein CName für uberbus ist.

**Comment by fpletz** [comment]
Ich denke nicht, dass wir sowas brauchen wenn nach mehr als 6 Jahren keiner sowas simples gebaut hat.
