### ISSUE TITLE
Agileres Schließsystem für Getränkelager

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#51]
Dailspeed Spezial Firmware für Matekratie schreiben:
Soll neben festem Code auch $Anzahl one-time-codes enthalten den man vertrauenswürdigen Leuten z.B. per IRC weitergeben kann

**Comment by pc-coholic** [comment]
Kann man das nicht vielleicht/lieber als einen weiteren Luftschleusen-Punkt machen?

Ein extra git-repo mit nur den Leuten, die diese eine Tür dann benutzen dürfen sollte ja machbar sein. Einmal-Berechtigungen kann man vermutlich ebenso bzw. ähnlich umsetzen.

**Comment by saerdnaer** [comment]
Vorschlag von Ray: Anstatt [Dailspeed](http://www.masterlock.com/personal-use/product/1500eXD) lieber [Noke](http://fuzdesigns.com/pages/noke) nehmen. Für mehr Details zum Noke (Spricht man wohl "No Key" aus) siehe auch https://www.kickstarter.com/projects/fuzdesigns/noke-the-worlds-first-bluetooth-padlock/description .

**Comment by morawekj** [comment]
Das Noke ist doch kaputt, das Dialspeed aber auch.
