### ISSUE TITLE
farbfernseher per IPv6 erreichbar machen

### ISSUE THREAD

**Issue by robinkaranu** [muccc/spacefoo#52]
Bitte per IPv6 verfügbar machen wenn es geht. Ansonsten ist er nur mit ekligem Tunnel über brezn ausm non-legacy Netz verfügbar.

**Comment by saerdnaer** [comment]
Man könnte alternativ auch irgendwo (z.B. auf der Brezn) einen Printserver mit CUPS o.ä. einrichten. Wäre langfristig eigentlich auch die sinnvollste Lösung.

**Comment by robinkaranu** [comment]
Man müsste mittelfristig an der Abschaltung von Legacy-IP für unsere Dienste arbeiten. Deshalb finde ich das ein unsicherer Printserver wie CUPS höchstens als Übergangslösung[tm] geeignet ist. ;-)

**Comment by robinkaranu** [comment]
Das manual des Druckers lässt leider böses vermuten. Man sieht überall nur Legacy-IP-Adressen, und die Suche findet nichts wenn man nach "IPv6" sucht. http://h20628.www2.hp.com/km-ext/kmcsdirect/emr_na-c00435218-1.pdf
