### ISSUE TITLE
„Borg16“ Matrixdisplay wieder mit Strom versorgen.

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#53]
Der „Borg16“ (grüne LED-Matrix mit unterhaltsamen wechselnden Anzeigeprogrammen) hängt im Hauptraum rechts unter der Luftschleusenmatrixanzeige.
Leider bekommt er momentan keinen Saft.
In der unmittelbaren Nähe finde ich auch keinen Versorgungsstrang.
Jemand mit deutlich mehr Hardwareknowhow als ich nehme sich der Sache bitte an.
Danke im Vorab.

**Comment by saerdnaer** [comment]
Wir haben jetzt eigentlich genügend Flipdot Anzeigen die eigentlich auch energiesparender sind und sinnvollere Dinge anzeigen. Aus meiner Sicht braucht es die Anzeige eigentlich nicht.
