### ISSUE TITLE
Rpi für Decken-ACAB deployen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#54]
Aus Gründen einer wünschenswerten, redundanten dezentralen Lichtsteuerungzentrale wäre es wünschenswert, die ACAB Lampen in der Decke an einen eigenen Rasberry Pi zu hängen, so dass diese auch dann funktioniert, wenn die Wand und der dazugehörige Netbook nicht da ist.

**Comment by derchrisuk** [comment]
Ich kann rPI Spenden. Sollte ja auch ein 1 fuer reichen.

**Comment by saerdnaer** [comment]
@derchrisuk Any updates? ;-)

**Comment by derchrisuk** [comment]
Ich habe mehrere Pi's bei mir im Spind.
Muss nur mal einer kommen und mitnehmen.
