### ISSUE TITLE
Mailing Listen Zukunft

### ISSUE THREAD

**Issue by codec** [muccc/spacefoo#55]
Jemand müsste mal eine Ansage machen, wie man weiter mit den Mailing Listen umgehen moechte.

Weiterhin mailman? Gibt es was "besseres"?

Feature Anforderungen haben sich IMO nicht geändert (MLs mit Crypto ist nach wie vor nervig).

@saerdnaer?

**Comment by saerdnaer** [comment]
Aus meiner Sicht sollten wir mal schauen wie weit unsere Anforderungen durch Mailman3 erfüllt werden. Allerdings gibts dafür noch keine Deb-Packages. Das Debian Mailman Team hat wohl keine Resourcen da selbst eines zu machen, freuen sich aber über Leute die das übernehmen ;-), vgl.: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783732 

> The current Debian Mailman team has very limited resources. I heartily
> invite anyone interested in packaging Mailman 3 to join the team and start
> working on it.

**Comment by saerdnaer** [comment]
Es gibt inzwischen jemand der sich darum kümmert. Laut https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799281#25 wollte er Ende Dezember 2015 fertig sein. Ist aber wohl noch nicht fertig, jedenfalls liefert https://packages.debian.org/search?keywords=mailman3 keine Ergebnisse.

**Comment by saerdnaer** [comment]
Hab mal nachgefragt, seine [Antwort](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799281#35):

> I successfully built something that made me happy, but so far I asked
> for some reviewing, and I got only one or two answers. I took the advice
> into account, I'll probably retry to ask some reviews soon, then I'll go in
> packaging all the things. My main issue for now is about configuring
> correctly mailman3 to have a properly running server on install, even if the
> administrator will need to reconfigure some things.

**Comment by saerdnaer** [comment]
Inzwischenzeit gibt es produktive Mailman3 Instanzen bei Arbeitgebern von Club-Mitgliedern. Allerdings gibts wohl aktuell noch keinen Import von Mailman2 Daten in eine Mailman3 Instanz.

**Comment by fpletz** [comment]
> Allerdings gibts wohl aktuell noch keinen Import von Mailman2 Daten in eine Mailman3 Instanz.

Dann muss man mal halt endlich aufräumen und alte Daten löschen. Wo ist das Problem?

Oder gleich auf etwas simpleres wie Schleuder? Denke das Webinterface benutzt eh keiner und das Archiv braucht man auch nicht ausser zum klugscheissen.

**Comment by codec** [comment]
![image](https://user-images.githubusercontent.com/118829/155856099-05df563b-5795-410c-96f9-9448c5d044bf.png)

**Comment by saerdnaer** [comment]
Ne, Webinterface sollten wir schon haben – Archiv haben wir ja keins ich glaube ich meinte damals einfach nur die Abbonenten und Config.
