### ISSUE TITLE
daily mv reminder

### ISSUE THREAD

**Issue by oida** [muccc/spacefoo#58]
22 20 \* \* \* andi MAILto=members@lists.muc.ccc.de java -jar /opt/hubel.jar /System/Library/Applications/apple.mail/meine_iphone_device_id.xml

**Comment by saerdnaer** [comment]
@0ida Kannst du mir mal im Club genauer erklären was du damit meinst?

**Comment by oida** [comment]
Die MV is erstmal vorbei, kann wieder zu ¯_(ツ)_/¯
