### ISSUE TITLE
Mails von OTRS werden aktuell nicht immer an presse@lists.muc.ccc.de weitergeleitet.

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#60]
Ich hab jetzt mal die entsprechendende Filterregel unter Privacy options -> Spam Filter in Mailman entsprechend angepasst, schauen wir mal ob es jetzt geht.

**Comment by saerdnaer** [comment]
Heute musste ich die mail wieder manuell freischalten... @codec Hast du mal Zeit/Lust das wir uns das gemeinsam anschauen?

**Comment by pc-coholic** [comment]
Hat sich mittlerweile durch die Umstellung von Bounce auf Notification erledigt
