### ISSUE TITLE
Muckekasterl in der Lounge

### ISSUE THREAD

**Issue by oida** [muccc/spacefoo#63]
In der Lounge werkelt gerade ein kleiner Mac Mini, hauptsächlich zwecks der Bassmassage, der ist allerdings zu lahm:
- Bewegtbild lagt
- jeder Versuch des Auflegens von $Musik wird mit nem Timestretching Effekt belohnt
- von external gear ganz zu schweigen (diese Traktor Decks, Mixer Konsole usw. - man würde sie auch benutzen wollen, am liebsten eingermaßen latenzfrei)
- und überhaupt!

Die Kiste hat nen Core2Duo und 2gb RAM.
1. SSD rein, RAM verdoppeln (hat noch wer?), OS neu installieren.
2. Wenn's nix hilft: Krautfanden? Was möchte man? Wer möchte?

**Comment by robinkaranu** [comment]
Ich unterstütze die bereits angeregten Bestrebungen, ergänze aber hiermit, dass auch mit SSD und mehr RAM der Mac Mini zu alt (-> nicht supported) für aktuelle Mac OS Versionen ist. Auch Traktor und Co läuft in mühsam zusammengesuchen legacy-Versionen. Hat jemand was neueres (> End 2009, scheinbar) von Apple am Start?

**Comment by oida** [comment]
Ach stimmt da war ja was - es sollte wohl wirklich wieder ein Mac sein damit entsprechende Software dann auch drauf rennt.
Das tut sie nicht unter Linux und Win kommt selbstredend ebenfalls nicht in Frage. Hackintosh wurde auch schonmal eruiert und leider für eingermaßen unbrauchbar befunden.
Damit ist Punkt 1. dann schonmal vom Tisch.

Aktuell ist OS X 10.11 (El Capitan) und dass sollte dann auch drauf laufen, diese devices kämen somit in Frage:
- iMac ab Mitte 2007
- MacBook Air ab Ende 2008
- MacBook ab Anfang 2009
- MacBook Aluminium ab Ende 2008
- MacBook Pro ab Mitte 2007
- Mac Pro ab Anfang 2008
- Mac mini ab Anfang 2009

Am günstigsten sind die Minis, die gibt es neu derzeit ab 569 €.
Ich glaube @argv hatte auch noch nen iMac günstig abzugeben, da is praktischerweise noch ein screen dran.
~~$jemand sollte in Erfahrung bringen wie viel man derzeit für nen gebrauchten Mac Mini löhnen muss~~ und dann abwägen und ggfs. Krautfanden.
Evtl. haben auch weitere Menschen noch devices günstig abzugeben.

~~Edit: _Mac Mini early 2009 geht wohl so ab ~320€ los._~~
Edit: Es ist ein iMac aufgetaucht! \0/

**Comment by saerdnaer** [comment]
Wenn jetzt iMac aufgetaucht ist kann man das Ticket ja schließen.
