### ISSUE TITLE
Leck Heizungsrohre im Keller, Bereich Lounge23/Lastenaufzug

### ISSUE THREAD

**Issue by robinkaranu** [muccc/spacefoo#64]
Ein Heizungsrohr im Keller ist undicht. Jemand muss einen Termin mit dem
Installateur ausmachen und ihn rein lassen. Ich schaffe es leider nicht
selbst.

Wenn sich jemand findet der Anfang nächster Woche telefonisch mit der Installationsfirma einen Termin ausmachen kann und sie reinlassen kann, bitte der HV Gött (und ggF. members@) auf folgendem Weg mitteilen:
hausverwaltung@spamfnord.de ODER Telefon 0808195XXXX

Wenn sich jemand findet kann ich gerne noch Bilder + Beschriebung hier attachen oder am WE direkt vor Ort zeigen was wo beobachtet wurde.

**Comment by saerdnaer** [comment]
Heute waren die Handwerker da und habend das Problem behoben
