### ISSUE TITLE
Neuen Wasserhahn fürs WC kaufen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#65]
Der Wasserhahn im WC tropft seit einigen Wochen und ist eigentlich eh die ganze Zeit schon der falsche Typ. Anbei mal ein paar Fotos aus dem Baumarkt:

![img_2063](https://cloud.githubusercontent.com/assets/40266/10542795/facb8732-741a-11e5-84cf-e9dd5293cbf8.JPG)
![img_2062](https://cloud.githubusercontent.com/assets/40266/10542798/fd6658fa-741a-11e5-9848-62fec539c7c6.JPG)
![img_2061](https://cloud.githubusercontent.com/assets/40266/10542800/ff058f00-741a-11e5-9ab6-3bab70b52236.JPG)

Vielleicht sollte man dieses Mal etwas mehr als beim letzten Mal ausgeben, nicht das man in 2 Jahren schon wieder einen Neuen kaufen darf.

**Comment by andz82** [comment]
ACHTUNG! aktueller Wasserhahn kann nur mit halber leistung betrieben werden. Sonst hat man einen wunderschoenen Springbrunnen im Klo...Deshalb niemals unter dem Waschbecken voll aufdrehen.

**Comment by saerdnaer** [comment]
Jan hat einen neuen gekauft und wird in einbauen

**Comment by pc-coholic** [comment]
#wasserhahngate durch @morawekj beendet.

**Comment by saerdnaer** [comment]
:+1:
