### ISSUE TITLE
Leere Getränkekisten unter Lautsprecherboxen in der Kellerlounge befreien

### ISSUE THREAD

**Issue by ACTPic** [muccc/spacefoo#66]
Da aktuell anscheinend keine einzige leere Getränkekiste mehr frei ist, die man in der Kellerlounge zum bequemen gesammelten Hochtransport der sich dort immer mal wieder materialisierenden Glasleergutansammlungen bereithalten könnte, sollte™ jemand™ irgendwann™ mal andere Stützen für die Boxen dort organisieren, um so zu ermöglichen, mindestens eins dieser da momentan fest verbauten Tragl wieder ihrem eigentlichen Einsatzzweck zuzuführen.

**Comment by saerdnaer** [comment]
Ihr könnt ja den Staender vom Tresor entsprechend zweitverwerten ;-)

**Comment by saerdnaer** [comment]
Die aktuelle Anzahl an Leergutkisten ist darauf ausgelegt, das der Matemat gefüllt ist. Aktuell ist das nicht der Fall, deswegen herrscht halt etwas Mangel. Lösung: Wieder Vollgut bei Getränkehändler gegenüber kaufen, vgl. https://wiki.muc.ccc.de/intern:matekratie#vollgut_kaufen
