### ISSUE TITLE
Webseite bzgl. public tuesday broken

### ISSUE THREAD

**Issue by Sec42** [muccc/spacefoo#67]
https://wiki.muc.ccc.de/ sagt "jeden Dienstag" - was nicht der Realität entspricht.
Bitte entweder Webseite oder Realität anpassen.

**Comment by saerdnaer** [comment]
Aktuell steht da "jeden Dienstag ab 20 Uhr, am 2. Dienstag im Monat ggf. auch mit ausführlicher Massenführung durch die Räume". Irgendwie stimmt das auch mit meiner persönlich gefühlten Realität überein. An sich stellt sich doch nur die Frage ob man die anderen Dienstage auch 'Public Tuesday' nennt, oder?

**Comment by Sec42** [comment]
Der letzten Dienstag den ich da war, war deutlich nicht-public und niemand fühlte sich zuständig.

**Comment by andz82** [comment]
worksforme - siehe Plenum 2016-01
