### ISSUE TITLE
weechat TLS auf brezn kaputt

### ISSUE THREAD

**Issue by datenwolf** [muccc/spacefoo#68]
Das weechat auf der brezn hat Motivationsprobleme TLS verschlüsselte IRC-Verbindungen (darkfasel, etc.) herzustellen. Irssi hat keine Probleme damit.

**Comment by saerdnaer** [comment]
Dast bei weechat mit dem darkfasel Netzwerk mehr oder weniger normal.

**Comment by fpletz** [comment]
@saerdnaer Nope, CACert halt.

**Comment by codec** [comment]
Seh ich keine Lösung für. Eher wird das gesamte System ersetzt.
