### ISSUE TITLE
Hauptraum: Lange Flipdotzeile Pixelfehler beheben

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#69]
Der 32C3 hat einige Pixelfehler bei der langen Flipdotzeile verursacht. Hat jemand Lust diese wieder zu beheben?

**Comment by andz82** [comment]
Darf sie auch jemand fixen der nicht wollte sie mitzunehmen? Oder auch
jemand der gar nicht auf dem 32C3 war?

**Comment by saerdnaer** [comment]
Ich hab den Text mal angepasst.

**Comment by derchrisuk** [comment]
Ich könnte das schon machen, allerdings kenne ich das Flipdot nicht so genau um den Aufwand einschätzen zu können.
