### ISSUE TITLE
AV Verstaerker im DHCP Netz auffindbar machen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#7]
Bitte Avahi-Reflection einrichten und ggf. auch Ports freischalten.

Vgl. http://tonylehnert.de/anchor/blog/andere-subnetze-sind-fur-airplay-neuland

**Comment by codec** [comment]
Bist Du dir sicher, dass das fuer den Onkyo reicht? Ich hab da auch einen zuhause und AFAIK macht der kein zeroconf.

**Comment by codec** [comment]
https://github.com/miracle2k/onkyo-eiscp/blob/master/eiscp/core.py#L266-L281

**Comment by saerdnaer** [comment]
Hmm, hab grade zufaellig die selben Zeilen gelesen. ;-) Man könne mal nen Pythonskript bauen das den Verstaerker im DHCP Netz simuliert und lass dass dann auf der uberbus vm laufen.

Im Prinzip muss man nur auf Port 60128 hören und dann auf `!xECNQSTN` mit `!1ECNTX-NR616/60128/XX/0009B0CB2E14` antworten.

Naja, vorerst kann man ja jetzt eh das Webinterface unter http://uberbus.club.muc.ccc.de:8083/openhab.app?sitemap=onkyo#_0000 nutzen

**Comment by saerdnaer** [comment]
Es ist doch ein bisschen mehr. Ich hatte UDP und Protokoll Header vergessen. Die Doku befindet sich in http://michael.elsdoerfer.name/onkyo/ISCP-V1.26_2013.xlsx auf einem der ersten Tabellenblätter. Aber an sich kann man auch einfach Teile des codes von https://github.com/miracle2k/onkyo-eiscp verwenden. Für mein konkretes Problem hab ich mir jetzt via OpenHAB nen Webinterface gebaut. Wenn jemand Lust hat den Eiscp Refelktor trotzdem noch zu bauen, kann ich gerne dabei helfen.
