### ISSUE TITLE
Spaceapi_Visualisation lokal aufsetzen und auf alle 4 Status aufbohren

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#70]
https://github.com/bastinat0r/Spaceapi_Visualisation

@fpletz was hällst du von der Idee, bzw. was hällst du von couchdb. Oder sollen wir lieber die Version aus von @florolf aus Karlsruhe (afaik mehre 2D Plots jeweils 7 Wochentage x 24h mit Codierung des Status per Farbe) lokal bei uns aufsetzen?

**Comment by fpletz** [comment]
@saerdnaer @florolf Wo ist der Code? :smiley_cat:

**Comment by derchrisuk** [comment]
Der hier? https://github.com/bastinat0r/Spaceapi_Visualisation

**Comment by fpletz** [comment]
Die von florolf.

**Comment by saerdnaer** [comment]
@florolf Wo findet man den deinen Code?

**Comment by fpletz** [comment]
Ich glaube das können wir uns sparen. Die neue API bietet Metrik-Support für Prometheus.
