### ISSUE TITLE
https://lists.muc.ccc.de wirft 502 Bad Gateway

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#71]
Ist inzwischen seit drei Tagen so. 
@codec, @fpletz Kann einer von euch das zweinah beheben und ggf. auch gleich nen Monitoring dafür einrichten?

Danke im voraus,
Andi

**Comment by fpletz** [comment]
:no_entry_sign: :lock: :no_good:

**Comment by codec** [comment]
Faileria beim austauschen der SSL Zertifikate ... :boom: Apache.
