### ISSUE TITLE
SSL settings otrs.muc.ccc.de

### ISSUE THREAD

**Issue by codec** [muccc/spacefoo#74]
https://www.ssllabs.com/ssltest/analyze.html?d=otrs.muc.ccc.de

/cc @pc-coholic

**Comment by pc-coholic** [comment]
Darf ich im Gegenzug auch wieder an dem "Wir brauchen Spamfilter"-Ticket rumalarmieren?  ;-)

**Comment by pc-coholic** [comment]
Sicherheitsschwankung auf T(A) minimiert.
