### ISSUE TITLE
Deckenacab nur zu 50% abschaltbar

### ISSUE THREAD

**Issue by andz82** [muccc/spacefoo#76]
Da die zum Fenster gewandte ACAB-Deckenzeile nun am selben Netzteil wie die wall haengt, ist mit der Fernbedienung nur noch die zur Wand gewandte Zeile abschaltbar.

Moegliche Loesung: Neues Netzteil in die Decke werfen

**Comment by saerdnaer** [comment]
Mögliche Lösung: Abschaltung Decke in Software implementieren.

**Comment by saerdnaer** [comment]
TODO: zusätzlichen Schalter im OpenHAB + für ACAB Decke abschalten umsetzen.

**Comment by saerdnaer** [comment]
Inzwischen kann man das per REST Endpoint unter http://acab2.club.muc.ccc.de:5000 abschalten – sowohl gesamt ACAB als auch nur Decke oder Wand.
vgl. https://github.com/muccc/acab-streetlife/blob/master/web-control-server.py

Um das Deckenacab auszuschalten braucht es z.B. ein 
`curl -X DELETE http://acab2.club.muc.ccc.de:5000/acab/decke`
um es wieder einzuschalten ein 
`curl -X POST http://acab2.club.muc.ccc.de:5000/acab/decke`

**Comment by saerdnaer** [comment]
Gibt jetzt auch in neuen OpenHAB Menü Einträge dafür: 
* https://github.com/muccc/openhab2-config/blob/master/items/lights.items#L8-L9
* https://github.com/muccc/openhab2-config/blob/master/sitemaps/default.sitemap#L12-L13
