### ISSUE TITLE
Licht im Hauptraum nur schaltbar wenn Hauptstrom an

### ISSUE THREAD

**Issue by andz82** [muccc/spacefoo#77]
Wenn man zuerst den Hauptstrom abschaltet, kann man das Licht im Hauptraum nicht mehr abschalten
@saerdnaer

**Comment by saerdnaer** [comment]
Da muss @morawekj o.ä. eine Dauerstrom-Steckdose neben der Verteilung im EG setzen.

**Comment by saerdnaer** [comment]
Da das Netzteil dafür jetzt auch ausgefallen ist – haben wir da in der Nähe zufällig schon irgend eine Niederspannungsquelle die am Dauerstrom hängt?

**Comment by saerdnaer** [comment]
Ich habe aktuell keine Zeit mich darum zu kümmern. Es wird doch wohl noch jemand anders im Club ein Netzteil mit 6V mit ~3A (oder was auch immer man für die Relais braucht) auftreiben können, oder?

**Comment by schneider42** [comment]
6 V scheint mir eine sehr spezielle Anforderung

**Comment by saerdnaer** [comment]
Wir können auch die 12 AC Relais und die 5V des RPi's auf zwei getrennte Netzteile legen....

**Comment by saerdnaer** [comment]
Grade getestet: Licht lässt sich auch schalten wenn Hauptstrom aus. Für Netzteil extra Ticket öffnen.

**Comment by saerdnaer** [comment]
Nachtrag: Die Steckdose war wohl schon die ganze Zeit am Dauerstrom – damit war der Auslöser des Tickets nicht valide ;-)
