### ISSUE TITLE
SSL Cert auf lists.muc.ccc.de

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#79]
Firefox 46.0.1 lässt mich nicht mehr auf https://lists.muc.ccc.de/cgi-bin/mailman/listinfo, Grund: SEC_ERROR_CERT_SIGNATURE_ALGORITHM_DISABLED

Ich konnte ihm leider nicht entlocken, welche Signatur er genau damit meint...

https://www.ssllabs.com/ssltest/analyze.html?d=lists.muc.ccc.de&hideResults=on meint nur "Chain issues, Incorrect order" sprich muc.ccc.de -> CAcert Class 3 Root -> CA Cert Signing Authority anstatt  CA Cert Signing Authority -> CAcert Class 3 Root -> muc.ccc.de

**Comment by saerdnaer** [comment]
Problem ist noch aktuell:
<img width="721" alt="temo" src="https://cloud.githubusercontent.com/assets/40266/20144947/8a75b144-a69e-11e6-94d0-3ea264030fec.png">

**Comment by codec** [comment]
![A+ seit 33c3~ish](http://i.imgur.com/VRbUDb7.png)
