### ISSUE TITLE
Mehr Speicher für uberbus VM wagen!

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#80]
Die Flukso-Stromverbrauchvorratsdatenspeicherung von @schneider42 brauch mehr Platz auf auf der uberbus vm. Bitte mehr HDD Speicher zur Verfügung stellen.

Danke im voraus,
Andi

Full disclosure: @fpletz meinte ich soll dieses Ticket anlegen.

**Comment by schneider42** [comment]
Ich wusste gar nicht, dass das ding noch Daten sammelt.

**Comment by fpletz** [comment]
@schneider42 Dann können wir die 2.2G ja löschen, oder?

**Comment by schneider42** [comment]
Unklar, ich werd mit den Daten wohl nichts machen...

**Comment by schneider42** [comment]
Aber was sind schon 2.2 GB ;)

**Comment by saerdnaer** [comment]
Die VM hat 5GB HDD Speicher. Wir haben gestern das flukso stromverbrauchloging im crontab des users flukso auskommentiert, die power.db runtergeladen und auf uberbus geloescht. Damit sollte das OpenHAB1 auf der VM wieder stabiler laufen.

**Comment by saerdnaer** [comment]
8. Februar 2018, #ccc 
```
<andi> Fehlerursache: Platte auf uberbus war voll. 25% des Plattenplatz wurden durch ngnix access logs belegt
<andi> hab die ngnix access logs jetzt mal deaktivert
<andi> Warum war bei dem ngnix IPv4 deaktivert? ```
