### ISSUE TITLE
Wiki-Thumbnails: Bilder werden nicht korrekt gedreht

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#81]
Anscheinend kann das Dokuwiki auf wiki.muc.ccc.de aktuell an manchen Stellen nicht richtig mit Hochkant-Bildern aus Smartphone umgehen. Beispiel: 
https://wiki.muc.ccc.de/_media/luftschleuse2:luftschleuse2_klingel.jpg vs. https://wiki.muc.ccc.de/_media/luftschleuse2:luftschleuse2_klingel.jpg?t=1455052318&w=500&h=375&tok=8e64ca vs. https://wiki.muc.ccc.de/start?image=luftschleuse2%3Aluftschleuse2_klingel.jpg&ns=luftschleuse2&tab_details=view&do=media vs. https://wiki.muc.ccc.de/luftschleuse2

@alice-wl Kann man da irgendwas umstellen, damit der Fehler nicht mehr auftritt?

**Comment by alice-wl** [comment]
Die orientierung steht im exif tag und die wird vom browser absichtl. ignoriert. Css4 koennte das fixen wird aber nirgends supportet.
Hab mal testweise mit imagemagic -auto-orient eine 401px version erstellt. Funktioniert leider nicht wenn nur die hoehe angegeben wird da die zielbreite auf basis des nicht rotierten bildes berechnet wird.
Ich sehe hier keine moeglichkeit das automatisch zu loesen.

https://developer.mozilla.org/en/docs/Web/CSS/image-orientation#Browser_compatibility
http://keyj.emphy.de/exif-orientation-rant/
