### ISSUE TITLE
OpenHAB 2.0 aufsetzen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#83]
https://community.openhab.org/t/openhab-2-0-beta4-has-been-released/14110

**Comment by derchrisuk** [comment]
Gestern wurde bereits ein rPI 3 mit OpenHAB 2 aufgesetzt, und Licht/ACAB Steuerung getestet.
Ebenso wurde bereits ein erster Homekit Test erfolgreich gestartet.
Geplant is komplett auf OpenHAB 2 umzusteigen.

**Comment by schneider42** [comment]
Hauptsache ich kann dann ueber andis iPhone mit siri quatschen

**Comment by saerdnaer** [comment]
Der Pi von Chris ist inzwischen im EG-Rack aka Anzeiger-Tür verbaut. Ggf. sollte man noch von WLAN auf LAN umstellen und entsprechende Firewall Regeln im Router einrichten, damit er nicht von außen erreichbar ist. Einfaches umziehen ins Hardware-Netz geht nicht, weil gewissen Dienste wie z.B. die Autodiscovery-Funktionalitäten erzwingen, dass das Gerät im selben Layer2 Netz ist. Die Uberbus VM ist ja deswegen z.B. auch in beiden Netzen.

**Comment by saerdnaer** [comment]
OpenHAB 2.0 wurde inzwischen aufgesetzt.
@derchrisuk Du meintest ja wir sollten das noch auf den HexaPi mit umziehen. Das ist aktuell ein Raspberry Pi 1. Weißt du zufällig ob das ausreicht, oder sollten wir den OpenHAB PI dorthin umziehen?

**Comment by derchrisuk** [comment]
Ich wuerde das auf dem 3er machen, because Java

**Comment by saerdnaer** [comment]
Wurde inzwischen umgesetzt.
