### ISSUE TITLE
Umfrage: Status 'closed' in 'restricted' umbenennen?

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#85]

**Comment by andz82** [comment]
Dagegen:
1. Verwirrt nur und aktuelle Bezeichnung ist bei allen bekannt
2. Passt vom Text her nicht auf Status Flipdot

**Comment by morawekj** [comment]
Blinder Aktionismuss, dagegen.

1. Sollte nun jedem member bekannt sein.
2. Für Aliens ist closed eindeutiger.

**Comment by codec** [comment]
GitHub ist kein vom Plenum akkreditiertes Demokratie-Werkzeug. Ha!
