### ISSUE TITLE
Die Spülung am WC ist defekt, Wasser fließt dauerhaft

### ISSUE THREAD

**Issue by robinkaranu** [muccc/spacefoo#87]
Nach dem altbekannten 'Button kommt nicht mehr raus und Wasser fließt deshalb durch den Spülkasten'-Bug, scheint es jetzt auch einen 'Button wird rausgezogen, aber Wasser fließt weiter durch den Spülkasten'-Bug zu geben.

Ich glaube wir wollen das verifzieren (ein Privatspähregeschützter Nerd hat schonmal investigiert - Ergebnis habe ich aber nicht mehr mitnehmen können) und die Hausverwaltung informieren. 

Weitere Beobachtungen, Ideen, Fragen oder Meinungen? Wenn mir niemand zuvor kommt, kümmer ich mich mal, in meiner Geschwindigkeit.

**Comment by morawekj** [comment]
Spülkasten müsste minimum zerlegt, gereinigt und mit neuen Dichtungen versehen werden, eigentlich schon über Bagatellgrenze, --> eigentlich Hausverwaltung.

**Comment by saerdnaer** [comment]
Der Sanitär-Mensch des Vertrauens der Hausverwaltung wäre am Dienstag wieder im Haus...

**Comment by robinkaranu** [comment]
Jetzt gerade schien sie wieder zu funktionieren (mit rausziehen). Ich bin am Dienstag vermutlich da und könnte den Menschen vermutlich schon mal zu unserem WC bringen, wenn das jemand entscheiden will. Ich weiß nicht.

**Comment by robinkaranu** [comment]
Der Sanitär-Mensch war da, hat sich die Spülung angeschaut. Er meint es reicht den Schwimmer zu tauschen und er kommt morgen oder übermorgen dazu vorbei. Er hat die Abdeckung offengelassen, damit wir so erstmal 'manuel spülen' können.

**Comment by schneider42** [comment]
Wir sollten einen Motor und einen RPi mit bluetooth verbauen. IoT!

**Comment by robinkaranu** [comment]
Ein neuer Schwimmer wurde heute eingebaut, der Spülkasten etwas gereinigt. Der nicht zurückkommende Button ist in einer Vermutzung am Button selbst geschuldet und wurde vom Handwerker zunächst mit einem Sprühstoß 'Kettenfett' gelöst. Mal sehen wie gut/lange das funktioniert.. ;-) Durchschlag vom Einsatzbericht für eventuelle Rückfragen ging an vorstand@. Gn8! :-)

**Comment by pc-coholic** [comment]
:raised_hands: :poop: :raised_hands:
