### ISSUE TITLE
AV-System unbenutzbar

### ISSUE THREAD

**Issue by schneider42** [muccc/spacefoo#89]
Alle Links auf http://wiki.muc.ccc.de/av:start sind entweder tot oder haben keine Option um das AV-System zu steuern.

Audio via Klinke funktioniert nicht. Druecken beliebiger Knoepfe mit und ohne eingeschaltetem Projektor haben keine Besserung gebracht.

Kein HDMI-Kabel am Tisch verfuegbar

Chromecast wird bei mir im 5Ghz legacy Netz nicht gefunden

**Comment by saerdnaer** [comment]
Hat jemand damit Erfahrung HDMI Stecker ode Buchsen anzulöten oder ein dafür passenden/nutzbares Kabel-Test-Gerät?

**Comment by saerdnaer** [comment]
Vgl. auch https://www.youtube.com/watch?v=gtNR5tAO01M und https://www.beamerforum.de/BBForum/threads/2796-HDMI-Stecker-selber-löten-Erfahrungsbericht

**Comment by saerdnaer** [comment]
Der OpenHAB Link auf [[av:start]] sollte inzwischen auch wieder gehen, vgl. http://83.133.178.106/classicui/app oder http://83.133.178.106/basicui/app

TODOs:
* [ ] OpenHAB1 auf uberbus deaktivieren `update-rc.d -f openhab remove`
* [ ] Onkyo wieder ans Netzwerk anschließen
* [ ] Eingang des Onkyo per Menü wieder auf Analog stellen
* [ ] Alle Kabel mit Eingangsbezeichnung des Onkyo beschriften (Klinkenkabel wurde angeblich getauscht – Verkablung ist aktuell nicht symmetrisch)
* [ ] Chromecast testen
* [ ] Neuen HDMI Stecker oder Buchse an defektes Kabel montieren

**Comment by saerdnaer** [comment]
HDMI Kabeltestgeräte gibts ab 17 EUR – http://www.ebay.de/sch/i.html?_nkw=hdmi+kabeltester&_sacat=0  Die sehen allerdings einfach nach RJ45/Ethernet-Tester mit anderen Buchsen aus und testen deswegen nur 9 Adern. Die teureren Tester testen 14 Adern. https://www.purelink.de/commercial-connectivity/installationszubehoer/pureid-serie/id-pt-1-kabeltester/

Nutzbare Stecker oder Buchsen kosten wohl so 10 EUR:
* https://www.amazon.de/Lyndahl-Steckverbinder-Stecker-Konfektionieren-Crimpverfahren/dp/B004I8YX0S/ref=pd_sim_107_1?_encoding=UTF8&psc=1
* Delock Terminalblock 
  * ~7 EUR https://www.reichelt.de/?ACTION=3&LA=446&ARTICLE=113234
  * ~10 EUR https://www.amazon.de/DeLock-65168-Adapter-Terminalblock-HDMI-Bu/dp/B003BCQP80/
  * https://www.conrad.de/de/hdmi-steckverbinder-buchse-einbau-vertikal-polzahl-22-conrad-components-1-st-1307037.html
* Aliexpress (leider >22 Tage Lieferzeit)
  * https://de.aliexpress.com/item/New-K5-200K-HDMI-module-free-solder-wire-twist-definition-hdmi-cable-with-wall-plug-with/32795583421.html
  * https://de.aliexpress.com/item/1-4-3D-HDMI-Female-Modular-Socket-WALL-Plate-NO-NEED-Soldering-diy/32615749925.html
  * https://de.aliexpress.com/item/HDMI-male-connector-with-screw-connector/32600169265.html

* Stecker zum Löten (macht aber glaube ich nicht wirklich Spaß)
  * https://www.reichelt.de/?ACTION=3&LA=517&ARTICLE=109547

**Comment by schneider42** [comment]
Wollen wir nicht lieber gleich in einen CAT5 basierten Extender investieren? Am besten dann fix im Kabelkanal verbaut und mit einer kleinen Verlaengerung zu den Tischen.

**Comment by derchrisuk** [comment]
Bekommt man schon für 30-40 Euro

**Comment by saerdnaer** [comment]
Aktueller Workaround: Es gibt jetzt wieder ein VGA Kabel am Haupttisch – damit geht überraschender weise auch Full HD mit 60 fps.

**Comment by saerdnaer** [comment]
https://wiki.muc.ccc.de/intern:plenum-2017-01 am 13. März 2017:
> Schneider erhaelt zweckgebunden 242 euro als budget fuer eine angebrachte audio/video loesung fuer die nordseite des hauptraums

16. März 2017 #ccc 
[21:41:12] \<andi> s: https://www.amazon.de/dp/B001NYB4HU 
[21:43:53] \<derchris> https://www.ligawo.eu/hdmi-extender-125m-ligawo-6526650/a-6526650/

**Comment by schneider42** [comment]
Der Onkyo ist nicht mehr in der Lage den Chromecast via USB mit Energie zu versorgen. Ich nehme an, dass es ein Problem mit dem Netzteil im Onkyo gibt.

Edit:
Daher eventuell auch die Audioprobleme

**Comment by schneider42** [comment]
[onkyo_tx_nr_616_service_manual.pdf.pdf](https://github.com/muccc/spacefoo/files/888077/onkyo_tx_nr_616_service_manual.pdf.pdf)

Alles deutet auf einen defekt von Q3001 (Seite 46): USB und Ethernet funktionieren nicht.

http://repairalmostanything.com/thread/78/
> The IC is manufactured by Texas Instruments and has been the subject of Texas Instruments internal memo's for premature aging, and ultimately the decision to halt production before they'd planned. The part number is D830K013BZB300, Q3001.

**Comment by schneider42** [comment]
Siehe auch https://www.google.de/search?q=onkyo+dts+bga

**Comment by schneider42** [comment]
Reflowen von Q3001 hat leider keinen Erfolg gebracht. Ich sehe das Geraet als defekt an.

**Comment by saerdnaer** [comment]
Ich hab für HDMI-Teil des AV Systems einen entsprechenden Workaround eingebaut:
![temp](https://cloud.githubusercontent.com/assets/40266/24716229/92a301a6-1a2e-11e7-89ae-ec22ca06bf2a.png)

Man muss die Anlage ggf. vorher über die Fernbedienungen einschalten um die Quelle auswählen zu können:
![temp2](https://cloud.githubusercontent.com/assets/40266/24716423/496eba9c-1a2f-11e7-9c17-dc471df2ecf5.png)

(Die Lautsprecher werden natürlich weiter nicht angesteuert. Ggf. kann hat der Projektor aber auch einen eingebaut)

**Comment by saerdnaer** [comment]
Gestern war jemand da der meinte er hätte einen Audio-Verstärker übrig, Schneider klärt wie weit dieser unsere Anforderungen erfüllt.

**Comment by saerdnaer** [comment]
Inzwischen ist ein Audioverstärker mit mechanischen Schaltern aufgetaucht. Aktuell sind zwei der vier Lautsprecher angeschloßen. Vorschlag von schneider zur Usability Vereinfachung: Quellenschalter fest auf dem Klinkenstecker am Arbeitstisch stehen lassen.

**Comment by saerdnaer** [comment]
Anscheinend ist neue interim Verstärker etwas suboptimal: Die Pegel an den Lautsprechern-Klemmen sind nicht symmetrisch. Wir haben spaßeshalber mal die Lautsprecher auf der anderen Wandseite angeschloßen -> selbes Problem. Sprich liegt nicht an den Lautsprechern sondern definitiv am Verstärker. Wir haben das jetzt mal einfach über den Balance-Regler ausgeglichen.

**Comment by saerdnaer** [comment]
Ich habe gestern an das defekte HDMI Kabel am Arbeitstisch eine neue Buchse montiert. In meinem Test konnte erfolgreich wieder HDMI Signale einspeisen. Testquelle war Chromecast Stick, dessen Hintergrundbild auf dem Projektor in 1080P60? angezeigt wurde. Allerdings musste ich einen HDMI Splitter als Verstärker nutzen.

Nebenbemerkung: Das Kabel das wir da haben ist nicht grade Standardgemäß – es ist zwar 1:1 durchverbunden aber die Gruppen/Schirmungen werden nicht eingehalten. Anstatt den Schirm am Pin gegenüber anzulöten, ist das Werk manchmal auf die Idee gekommen, den Pin daneben zu nehmen. Bis auf die Clock wurden die +/- Paare allerdings nicht aufgebrochen. Siehe beide Tabellen unten.

Nützliche Links zum Thema:
* https://superuser.com/a/425519
* https://hdezlock.com/repairing-damaged-hdmi-cable/

![img_1045](https://cloud.githubusercontent.com/assets/40266/26035620/907574a8-38cf-11e7-8030-1636a9e952f3.JPG)
![img_1044](https://cloud.githubusercontent.com/assets/40266/26035623/91a8c5fa-38cf-11e7-963c-cd85894b63bb.JPG)

Belegung sortiert nach Pin Nr.
<img width="816" alt="Belegung sortiert nach Pin Nr." src="https://cloud.githubusercontent.com/assets/40266/26035688/b4d6634c-38d0-11e7-96d3-25dbcc12fd32.png">

Belegung sortiert nach Kabelgruppen
<img width="818" alt="Belegung sortiert nach Kabelgruppen" src="https://cloud.githubusercontent.com/assets/40266/26035714/e57f5378-38d0-11e7-9f3b-3d3ac12b07a4.png">

**Comment by saerdnaer** [comment]
Fpletz hatte die Tage auch nochmal den neuen Anschluss am Tisch getestet: Bei ihm hat die Buchse direkt (via Displayport Adapter) funktioniert, allerdings gabs bei 1080P60 grüne Artefakte. Manueller Wechsel auf 1080i60 hat das behoben. Sprich eine Langzeitlösung sieht anders aus, vgl. #95
