### ISSUE TITLE
Tresor aus dem Innenhof entfernen

### ISSUE THREAD

**Issue by dl1com** [muccc/spacefoo#9]
Um an der Hintertür der Clubräume die genehmigten Sitzgelegenheiten etc. aufstellen zu können, müsste der Tresor von dort entfernt werden.

**Comment by saerdnaer** [comment]
Wenn das mit dem Keller nicht zeitnah klappt, würde ich ihn erst mal in den Flur stellen. Da wo momentan die Getränkekisten stehen.
Unabhänig davon kann man ihn doch gleich mal vom Bodengestell abschrauben, oder?

**Comment by saerdnaer** [comment]
Hat Jan inzwischen ein Angebot für den Transport eingeholt?

**Comment by saerdnaer** [comment]
Laut Jan, gibt es nach dem Wochenende ein Update.

**Comment by saerdnaer** [comment]
@morawekj gibts da Neuigkeiten?

**Comment by saerdnaer** [comment]
Ich wäre dafür den jetzt einfach in den Flur zu stellen

**Comment by einanderer** [comment]
Ich bin dagegen.

1.) Platzverschwendung auf eh begrenzten  Raum im Flur, wohin dann mit den Getränkekisten? Öffnen der Aufzugstür usw.
2.) Niemand kennt die Traglast des Bodens. Es ist Doof wenn der dann zwei Wochen später zwar am Ziel ankommt, im Keller, aber nicht die Treppe benutzt wurde ;)

**Comment by saerdnaer** [comment]
@9R Was ist deine Meinung als Bauingenieur zum Thema "Traglast des Bodens"?

**Comment by andz82** [comment]
Naja, spätestens im Frühling wenn wir die Anti-Fahrrad-Sitzecke hinbauen, muss er weg...
Bzw: ich Kauf mal noch n Schild "Fahrräder anlehnen verboten"

**Comment by dl1com** [comment]
Was ist denn nun mit dem Dienstleister der das Ding ordnungsgemäß in den Keller transportiert? 
Zu teuer, nicht möglich, noch nicht angefragt? Man muss ja wahrscheinlich kein Tresorexperte sein um da mal einen Kostenvoranschlag anzufordern, oder? X mal Y mal Z groß, ca ganz schön schwer, 1 Stockwerk, danke.
Dann brauchen wir uns nicht um Zwischenlösungen kümmern... -.-

**Comment by dl1com** [comment]
Habe rfguy nochmal getriggert, frägt bei der Firma nochmal nach was nun los ist.

**Comment by einanderer** [comment]
Die Anfrage wollte Jan halten.

Ich halte es auch für Sinnbefreit 600kg +|- x kg in den Flur zu schieben um ihn dann wieder rauszuschieben, da er nur über die Kellertreppe in der Heßstr. In den Keller befördert werden kann. Unsere Treppe im Club schafft den Safe definitiv nicht.

**Comment by 9R** [comment]
Pi*Daumen: Decken in Wohnräumen sind meist für ~200kg/m² ausgelegt, bei
Gewerbe ohne besondere Anforderungen ~300kg/m². Die Werte beziehen sich
auf gleichzeitige & -mäßige Belastung der gesamten Fläche. Einzellasten
dürfen also auch mal höher sein. Wieviel höher hängt vor Allem von der
Beschaffenheit der Decke und vom Abstand zu tragenden Wänden ab. Im
Altbau kann die Tragfähigkeit aber auch deutlich nach unten abweichen.

Ohne Einsicht in Unterlagen zur Statik des Gebäudes bzw zum Aufbau der
Decke kann ich da nichts belastbares (pun intended) zu beitragen.

Abgesehen davon, dass ich André im Bezug auf Platzmangel im Gang
zustimme, mein Tip: Vor spontanem TresorInDenGangGezerre mal den Götz
konsultieren, ob er weiß was die Decke aushält bzw ihn in Kenntnis
setzen, dass der Tresor da hin soll.

**Comment by saerdnaer** [comment]
Ich hatte meinen Vorschlag nicht als Zwischenlösung gedacht, mir persönlich gefällt die Variante besser, weil man dann nicht immer extra in den Keller muss, um z.B. die Wärmebildkamera zu holen. 
Bevor wir das aber diskutieren, sollen wir erst mal den Preis für den 'professionellen Transport' erfragen.

**Comment by saerdnaer** [comment]
Anfrage an Gött ist raus.

**Comment by saerdnaer** [comment]
Es gibt wohl keine Unterlagen zur Statik des Gebäudes. Gött will sich das am 24. März selbst persönlich anschauen

**Comment by robinkaranu** [comment]
Ich hab letzte Woche einen möglichen Aufstellort mit Herrn Gött abgesprochen, nämlich direkt an der Wand in der Ecke am Aufgang zum Zwischengeschoss. Ich würde das noch im nächsten Plenum einbringen und bei Zustimmung den Tresor an die entsprechende Position moven (lassen).

**Comment by saerdnaer** [comment]
Plenum 2015-03: Tresor soll weg und nicht im Club aufgestellt werden.

**Comment by saerdnaer** [comment]
@markus2342 Was ist der aktuelle Stand?

**Comment by saerdnaer** [comment]
Nachbar (Schreinerei) hat Interesse angemeldet.

**Comment by saerdnaer** [comment]
Nachbar will ihn jetzt wohl doch nicht.

**Comment by robinkaranu** [comment]
Der Tresor ist weg, ich mach das mal zu. Danke an die vielen Beteiligten für das schlussendlich erfolgreiche Lösen des Problems. :+1:
