### ISSUE TITLE
Heizung zeigt unspezifizierzen Fehler an

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#92]

**Comment by saerdnaer** [comment]
Hab bei der HV angerufen: Heizunngshandwerker wird umgehend informiert

**Comment by fpletz** [comment]
Heizung scheint zu funktionieren.

**Comment by schneider42** [comment]
Funktioniert die Heizung oder zeigt sie keinen Fehler mehr an?

**Comment by saerdnaer** [comment]
Heizkörper werden wieder warm.
