### ISSUE TITLE
HDMI over Cat7 Kabel Übertrager beschaffen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#95]
Wie bereits in https://github.com/muccc/spacefoo/issues/89#issuecomment-287803357 angerissen:

https://wiki.muc.ccc.de/intern:plenum-2017-01 am 13. März 2017:
> Schneider erhaelt zweckgebunden 242 euro als budget fuer eine angebrachte audio/video loesung fuer die nordseite des hauptraums

16. März 2017 #ccc 
[21:41:12] \<andi> s: https://www.amazon.de/dp/B001NYB4HU 
[21:43:53] \<derchris> https://www.ligawo.eu/hdmi-extender-125m-ligawo-6526650/a-6526650/

**Comment by derchrisuk** [comment]
HDBaseT Class B

Aten VE801T Sender - https://www.cyberport.de/aten-ve801t-hdmi-hdbaset-lite-sender-hdbaset-class-b--4B19-0M0_11569.html
Aten VE801R Emfpaenger - https://www.cyberport.de/?DEEP=4B19-0LZ&APID=117&gclid=CJ-LloaOiNQCFQeNGwoduYQEcg

**Comment by schneider42** [comment]
Hab mal den ligawo bestellt. Mal sehen ob das funktioniert.

**Comment by schneider42** [comment]
http://www.lindy.de/HDMI-IR-Cat-6-Extender-mit-Monitorport-50m.htm?websale8=ld0101&pi=38144&ci=200202

**Comment by schneider42** [comment]
Der Ligawo war doof, ist wieder zurueck gegangen. Haben jetzt mal den Lindy bestellt.

**Comment by saerdnaer** [comment]
Wir haben einen Lindy 38144 (50m über Cat6 Kabel) beschafft. Der Sender ist nun über ein provisorisches 15m Cat5 Kabel, das direkt zwischen Verstärker und Tisch verlegt wurde, mit dem Empfänger verbunden. Die Kabellänge muss manuell über einen 4-Bit DIP Schalter eingestellt werden – für Festinstallationen vielleicht vertretbar, macht spontane Umbauten aber er eher kompliziert. 

Testverkablung über bestehende Kabelinfrastruktur führte nicht zum Erfolg.  Nochmal mit dediziertem Cat6/7 Kabel direkt vom Verstärker zum Rack testen. Das ist aber eigentlich ein eigenes Issue – der Übertrager selbst wurde ja jetzt beschafft.
