### ISSUE TITLE
Podcast Hardware: H6 beschaffen

### ISSUE THREAD

**Issue by saerdnaer** [muccc/spacefoo#96]
* [ ] Innenmaße des alten Koffers feststellen
* [ ] Passendes Modell finden, z.B. https://www.thomann.de/de/flyht_pro_wp_safe_box_3_ip65.htm o.ä.
* [ ] Bei Plenum Finanzierung beantragen

**Comment by dergigo** [comment]
Ich habe einen geeigneten und stabilen Koffer, den ich dafür spenden würde.
Größe: etwas größer als der alte.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fpletz** [comment]
~~Was spricht gegen Crowdfunding? Der Club macht keine Podcasts mehr.~~

Neue Podcast-Initiative nicht bemerkt. Carry on. :+1:

**Comment by saerdnaer** [comment]
Koffer haben wir inzwischen, allerdings wurde der H6 beim Einbau in den Koffer beschädigt und wartet jetzt seit ca. einem halben Jahr auf Reperatur/Austausch. Solange gibt es ein festes Setup im Studio, vgl. 
![studio](https://user-images.githubusercontent.com/40266/36074505-e153d462-0f40-11e8-9ab9-1890412c30c7.jpg)

Für mobile Aufnahme Situationen wurden verschiedene kleinere Field-Recorder (H1, H4n, etc) von Mitgliedern angeboten...

**Comment by saerdnaer** [comment]
Am Dienstag ist nun euch der Ersatz-H6 eingetroffen, damit kann dieses Ticket geschlossen werden.
